FROM golang:1.21-alpine AS builder

WORKDIR /build

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ssh-proxy-server ./cmd/ssh-proxy-server

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /build/ssh-proxy-server /ssh-proxy-server

ENTRYPOINT ["/ssh-proxy-server"]